# This workflow builds and tests Cobigen

name: Maven Package

on: [push, pull_request]

jobs:
  build-and-test:

    strategy:
      matrix:
        # test against latest Java version 8 and 11:
        - javaVersion: [ 8, 11 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.javaVersion }}
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn clean install -e -U -Pp2-build-photon,p2-build-stable -T 1C
      #run: mvn clean install -e -U -Pp2-build-photon,p2-build-stable --fail-at-end
