# This workflow builds and tests Cobigen run in parallel and stops if one build doesn't work

name: build & test cronJob # on Ubuntu and Windows with OpenJDK8 and OpenJDK11

on: 
  - schedule:
    - cron: '0 16 * * *'
    - workflow_dispatch

jobs:
  build-and-test:

    strategy:
      matrix:
        # test against Java version 8 and 11:
        javaVersion: [ 8, 11 ]
        os: [windows-latest,ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.javaVersion }}
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn clean install -e -U -Pp2-build-photon,p2-build-stable --fail-at-end
